Pivot-Studio/pivot-lang

- .vscode/launch.json
- Cargo.lock
- Cargo.toml
- README.md
- src/ast/ctx.rs
- src/ast/mod.rs
- src/lexer/lexer.rs
- src/main.rs
- src/parser/math.rs
- src/parser/mod.rs
- src/utils/mod.rs
> feat: 增加四则运算

- Cargo.lock
- Cargo.toml
- src/ast/mod.rs
- src/lexer/pos.rs
- src/main.rs
- src/nomparser/mod.rs
- src/parser/math.rs
> refactor: use nom to parse

- Cargo.lock
- add_symbol/src/add_symbol_macro/src/lib.rs
- vm/Cargo.lock
- vm/Cargo.toml
- vm/src/gc/mod.rs
> feat: add basic gc

- .gitignore
- Cargo.toml
- internal_macro/src/add_symbol_macro/src/lib.rs
- src/ast/ctx.rs
- src/utils/test_symbol.rs
- vm/Cargo.lock
- vm/Cargo.toml
- vm/src/gc/mod.rs
- vm/src/lib.rs
> feat: update is_runtime

- src/ast/node/function.rs
- src/nomparser/mod.rs
注意：`/nomparser/mod.rs`这里需要在完成后去掉注释
> feat: func_call

- src/ast/compiler.rs
- src/ast/ctx.rs
- src/ast/diag.rs
- src/ast/node/function.rs
- src/ast/node/implement.rs
- src/ast/node/mod.rs
- src/ast/node/operator.rs
- src/ast/node/pkg.rs
- src/ast/node/primary.rs
- src/ast/node/program.rs
- src/ast/node/statement.rs
- src/ast/node/types.rs
- test/lsp/test_completion.pi
- test/main.pi
> struct支持引用自己的指针

- .github/workflows/test.yml
- README.md
- src/ast/ctx.rs
- src/ast/gcapi.rs
- src/ast/node/control.rs
- src/ast/node/function.rs
- src/ast/node/global.rs
- src/ast/node/implement.rs
- src/ast/node/mod.rs
- src/ast/node/operator.rs
- src/ast/node/pkg.rs
- src/ast/node/pointer.rs
- src/ast/node/primary.rs
- src/ast/node/statement.rs
- src/ast/node/types.rs
- src/ast/tokens.rs
- src/nomparser/structure.rs
- src/nomparser/types.rs
> refactor: use Rc<RefCell> for pltype

- src/ast/ctx.rs
- src/ast/diag.rs
- src/ast/node/function.rs
- src/ast/node/operator.rs
- src/ast/node/types.rs
- src/ast/pltype.rs
> 修复method模块外使用

- vm/src/gc/mod.rs
> fix: enhance point change

- Makefile
- src/ast/builder/llvmbuilder.rs
- src/ast/node/function.rs
- test/main.pi
- test/test/list.pi
- test/test/simple.pi
- alloc in alloc block
- malloc in current block except retval
- malloc retval in alloc block
> fix:malloc block

- Cargo.lock
- immix/benches/immix_bench.rs
> update: lld-rs

- Cargo.lock
- planglib/core/gc.pi
- planglib/core/panic.pi
- planglib/std/io.pi
- src/ast/fmt.rs
- src/ast/node/function.rs
- src/ast/node/types.rs
- src/ast/test.rs
- src/nomparser/comment.rs
- src/nomparser/function.rs
- src/nomparser/structure.rs
- src/nomparser/types.rs
- test/fmt/Kagari.toml
- test/fmt/test_fmt.pi
- test/fmt_windows/Kagari.toml
- test/fmt_windows/test_fmt.pi
- test/mod2.pi
- test/test/method.pi
- test/test/string.pi
- test/test/sub_module.pi
- test/test/traits.pi
> fix: where and pub fmt

- book/src/dev-prepare.md
- immix/src/collector.rs
- immix/src/lib.rs
- planglib/core/builtin.pi
- planglib/std/__private.pi
- planglib/std/stdbuiltin.pi
- src/ast/builder/llvmbuilder.rs
- src/ast/ctx.rs
- src/ast/ctx/builtins.rs
- src/ast/diag.rs
- src/ast/node/function.rs
- src/ast/node/macro_nodes.rs
- src/ast/node/primary.rs
- src/ast/node/program.rs
- src/ast/node/statement.rs
- src/ast/node/string_literal.rs
- src/ast/plmod.rs
- src/ast/pltype.rs
- src/ast/test.rs
- src/nomparser/function.rs
- src/nomparser/statement.rs
- test/main.pi
- test/test/compiletime_reflection.pi
- test/test/macros.pi
- test/tmod2.pi
- vm/src/gc/mod.rs
- vm/src/lib.rs
> feat: 支持编译期反射

- src/ast/builder/llvmbuilder.rs
- src/ast/compiler.rs
- src/ast/diag.rs
- src/ast/fmt.rs
- src/ast/node/function.rs
- src/ast/node/implement.rs
- src/ast/node/interface.rs
- src/ast/node/operator.rs
- src/ast/node/program.rs
- src/ast/node/statement.rs
- src/ast/node/string_literal.rs
- src/ast/node/tuple.rs
- src/ast/node/types.rs
- src/ast/test.rs
- src/flow/mod.rs
- src/nomparser/statement.rs
- test/fmt/test_fmt.pi
- test/main.pi
- test/test/deconstruct.pi
> feat: deconstruct

- src/ast/ctx.rs
- src/ast/node/types.rs
- src/ast/test_diag.expect
- test/lsp_diag/test_diag.pi
Fixes #290
generic types' self reference is still not checked in this pr
> self reference check

- src/ast/builder/llvmbuilder.rs
- src/ast/builder/mod.rs
- src/ast/builder/no_op_builder.rs
- src/ast/diag.rs
- src/ast/node/operator.rs
- src/ast/pltype.rs
- src/ast/tokens.rs
- src/nomparser/expression.rs
- test/test/simple.pi
> feat: add bitwise operators

- book/src/dev-prepare.md
- src/ast/diag.rs
- src/ast/expects/test_diag.pi.expect
- src/ast/expects/trait_diag.pi.expect
- src/ast/node/cast.rs
- src/ast/node/interface.rs
- src/ast/pltype.rs
- test/lsp_diag/trait_diag.pi
- test/test/multi_trait.pi
> 强化as和is功能，支持接口

- src/ast/ctx.rs
- src/ast/diag.rs
- src/ast/expects/test_diag.pi.expect
- src/ast/node/macro_nodes.rs
- test/lsp_diag/test_diag.pi
- test/test/macros.pi
> better macro

- immix/src/collector.rs
- immix/src/consts.rs
- planglib/core/gc.pi
- src/ast/builder/llvmbuilder.rs
- src/ast/node/macro_nodes.rs
- test/gcbench/Kagari.toml
- test/gcbench/README.md
- test/gcbench/main.pi
- vm/src/lib.rs
- vm/src/libcwrap/mod.rs
- fix: wrong auto collect condition
- fix: wrong macro expansion
> feat: add gc benchmark code

- src/nomparser/constval.rs
- test/test/simple.pi
like:
- 0x12_AA
- 0X21_cD
- 0o12_77
- 0O22_55
- 0b1100_0000
- 0B1100_1111
> feat: hexadecimal & binary number

- immix/src/allocator/big_obj_allocator.rs
- immix/src/allocator/global_allocator.rs
- immix/src/collector.rs
- immix/src/consts.rs
- src/ast/builder/llvmbuilder.rs
- src/ast/builder/mod.rs
- src/ast/builder/no_op_builder.rs
- src/ast/compiler.rs
- src/ast/ctx/lsp.rs
- src/ast/node/function.rs
> Performance Optimization todo

- src/ast/node/function.rs
- test/test/traits.pi
> when casting pointer type into trait implicitly result in wrong ir

- planglib/core/gc.pi
- planglib/core/string.pi
- src/ast/ctx/generic.rs
- src/ast/ctx/lsp.rs
- src/ast/diag.rs
- src/ast/node/tuple.rs
- src/ast/pltype.rs
- src/ast/test.rs
- src/inference/mod.rs
- test/test/tuple.pi
> cannot use methods implement on generic tuples

- src/ast/ctx.rs
- src/ast/node/global.rs
- src/ast/node/pkg.rs
- src/ast/node/program.rs
- src/ast/plmod.rs
- src/main.rs
- src/repl/editor.rs
- src/repl/mod.rs
- add headless REPL mode
- allow redefine symbol in repl mode
> feat: support jupyter notebook

- Cargo.lock
- Cargo.toml
- src/ast/accumulators.rs
- src/ast/builder/llvmbuilder.rs
- src/ast/compiler.rs
- src/ast/compiler/options.rs
- src/ast/diag.rs
- src/ast/expects/hinttest.expect
- src/ast/node/function.rs
- src/ast/node/program.rs
- src/ast/node/program/cycle.rs
- src/ast/node/program/salsa_structs.rs
- src/ast/plmod.rs
- src/ast/test.rs
- src/db.rs
- src/jar.rs
- src/lsp/lspserver.rs
- src/lsp/mem_docs.rs
- src/main.rs
- src/nomparser/mod.rs
- src/repl/completer.rs
- src/repl/mod.rs
- src/utils/read_config.rs
Well, previous salsa version has a [serious bug](https://github.com/salsa-rs/salsa/issues/473) which makes lsp deadlock from time to time,
I've fixed it in April, but somehow forget to update salsa orz.
> chore: update salsa to the latest version
